"""
Output generators for compatibility layers.

This module generates static catalog files in various formats:
- STAC (SpatioTemporal Asset Catalog)
- ISO 19139 (XML metadata)
- OGC API Records (future)
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING
from xml.etree import ElementTree as ET

if TYPE_CHECKING:
    from portolan import CatalogConfig


# =============================================================================
# STAC Generator
# =============================================================================

def generate_stac_catalog(catalog: "CatalogConfig", verbose: bool = False) -> dict[str, Path]:
    """
    Generate a static STAC catalog from Portolan resources.

    Creates:
    - catalog.json (root catalog)
    - collections/{namespace}/collection.json (per namespace)
    - collections/{namespace}/items/{id}.json (per resource)

    Args:
        catalog: CatalogConfig with path to .portolan directory
        verbose: Print progress

    Returns:
        Dict mapping STAC paths to created files
    """
    stac_dir = catalog.stac_dir
    stac_dir.mkdir(parents=True, exist_ok=True)

    resources_dir = catalog.path / "resources"
    if not resources_dir.exists():
        if verbose:
            print("No resources found, skipping STAC generation")
        return {}

    files_created = {}

    # Collect all namespaces and their resources
    namespaces = {}
    for namespace_dir in resources_dir.iterdir():
        if not namespace_dir.is_dir():
            continue

        namespace = namespace_dir.name
        namespaces[namespace] = []

        for resource_file in namespace_dir.glob("*.json"):
            if resource_file.name.startswith("_"):
                continue

            try:
                with open(resource_file) as f:
                    resource = json.load(f)
                namespaces[namespace].append(resource)
            except Exception as e:
                if verbose:
                    print(f"  Error reading {resource_file}: {e}")

    if not namespaces:
        if verbose:
            print("No resources found in any namespace")
        return {}

    # Create root catalog
    root_catalog = {
        "type": "Catalog",
        "stac_version": "1.0.0",
        "id": "portolan-catalog",
        "title": "Portolan Catalog",
        "description": "Geospatial data catalog generated by Portolan",
        "links": [
            {"rel": "self", "href": "./catalog.json", "type": "application/json"},
            {"rel": "root", "href": "./catalog.json", "type": "application/json"},
        ]
    }

    # Add collection links
    for namespace in namespaces:
        root_catalog["links"].append({
            "rel": "child",
            "href": f"./collections/{namespace}/collection.json",
            "type": "application/json",
            "title": namespace.replace("_", " ").title(),
        })

    # Write root catalog
    catalog_path = stac_dir / "catalog.json"
    with open(catalog_path, "w") as f:
        json.dump(root_catalog, f, indent=2)
    files_created["catalog.json"] = catalog_path

    if verbose:
        print(f"Created STAC catalog: {catalog_path}")

    # Create collections and items
    for namespace, resources in namespaces.items():
        collection_dir = stac_dir / "collections" / namespace
        items_dir = collection_dir / "items"
        items_dir.mkdir(parents=True, exist_ok=True)

        # Calculate collection extent from resources
        bbox = _calculate_collection_bbox(resources)
        temporal = _calculate_collection_temporal(resources)

        # Create collection
        collection = {
            "type": "Collection",
            "stac_version": "1.0.0",
            "id": namespace,
            "title": namespace.replace("_", " ").title(),
            "description": f"Collection of {len(resources)} resources",
            "license": "various",
            "extent": {
                "spatial": {"bbox": [bbox] if bbox else [[]]},
                "temporal": {"interval": [[temporal["start"], temporal["end"]]] if temporal else [[None, None]]},
            },
            "links": [
                {"rel": "self", "href": "./collection.json", "type": "application/json"},
                {"rel": "root", "href": "../../catalog.json", "type": "application/json"},
                {"rel": "parent", "href": "../../catalog.json", "type": "application/json"},
            ],
        }

        # Add item links
        for resource in resources:
            name = resource.get("name", "unknown")
            collection["links"].append({
                "rel": "item",
                "href": f"./items/{name}.json",
                "type": "application/geo+json",
                "title": resource.get("title", name),
            })

        # Write collection
        collection_path = collection_dir / "collection.json"
        with open(collection_path, "w") as f:
            json.dump(collection, f, indent=2)
        files_created[f"collections/{namespace}/collection.json"] = collection_path

        if verbose:
            print(f"Created STAC collection: {namespace} ({len(resources)} items)")

        # Create items
        for resource in resources:
            item = _resource_to_stac_item(resource, namespace)
            item_path = items_dir / f"{resource.get('name', 'unknown')}.json"
            with open(item_path, "w") as f:
                json.dump(item, f, indent=2)
            files_created[f"collections/{namespace}/items/{resource.get('name')}.json"] = item_path

    if verbose:
        print(f"Generated STAC catalog with {len(files_created)} files")

    return files_created


def _resource_to_stac_item(resource: dict, collection: str) -> dict:
    """Convert a Portolan resource to a STAC Item."""
    name = resource.get("name", "unknown")
    spatial = resource.get("spatial_extent", {}) or {}

    # Build bbox
    bbox = None
    if all(k in spatial for k in ["west", "south", "east", "north"]):
        bbox = [spatial["west"], spatial["south"], spatial["east"], spatial["north"]]

    # Build geometry from bbox
    geometry = None
    if bbox:
        geometry = {
            "type": "Polygon",
            "coordinates": [[
                [bbox[0], bbox[1]],
                [bbox[2], bbox[1]],
                [bbox[2], bbox[3]],
                [bbox[0], bbox[3]],
                [bbox[0], bbox[1]],
            ]]
        }

    # Build properties
    properties = {
        "title": resource.get("title", name),
        "description": resource.get("abstract", ""),
        "datetime": resource.get("created_at") or datetime.now(timezone.utc).isoformat(),
        "portolan:type": resource.get("type", "external"),
        "portolan:format": resource.get("format", "unknown"),
    }

    # Add temporal if available
    temporal = resource.get("temporal_extent", {}) or {}
    if temporal.get("start"):
        properties["start_datetime"] = temporal["start"]
    if temporal.get("end"):
        properties["end_datetime"] = temporal["end"]

    # Build assets
    assets = {}
    resource_assets = resource.get("assets", {})
    for asset_key, asset_info in resource_assets.items():
        if isinstance(asset_info, dict):
            assets[asset_key] = {
                "href": asset_info.get("href", ""),
                "type": asset_info.get("type", "application/octet-stream"),
                "title": asset_info.get("title", asset_key),
            }

    item = {
        "type": "Feature",
        "stac_version": "1.0.0",
        "id": name,
        "geometry": geometry,
        "bbox": bbox,
        "properties": properties,
        "assets": assets,
        "collection": collection,
        "links": [
            {"rel": "self", "href": f"./{name}.json", "type": "application/geo+json"},
            {"rel": "collection", "href": "../collection.json", "type": "application/json"},
            {"rel": "root", "href": "../../../catalog.json", "type": "application/json"},
        ],
    }

    return item


def _calculate_collection_bbox(resources: list[dict]) -> list | None:
    """Calculate bounding box that covers all resources."""
    west, south, east, north = float('inf'), float('inf'), float('-inf'), float('-inf')
    has_bbox = False

    for r in resources:
        spatial = r.get("spatial_extent", {}) or {}
        if all(k in spatial for k in ["west", "south", "east", "north"]):
            west = min(west, spatial["west"])
            south = min(south, spatial["south"])
            east = max(east, spatial["east"])
            north = max(north, spatial["north"])
            has_bbox = True

    return [west, south, east, north] if has_bbox else None


def _calculate_collection_temporal(resources: list[dict]) -> dict | None:
    """Calculate temporal extent that covers all resources."""
    start_dates = []
    end_dates = []

    for r in resources:
        temporal = r.get("temporal_extent", {}) or {}
        if temporal.get("start"):
            start_dates.append(temporal["start"])
        if temporal.get("end"):
            end_dates.append(temporal["end"])

    if start_dates or end_dates:
        return {
            "start": min(start_dates) if start_dates else None,
            "end": max(end_dates) if end_dates else None,
        }
    return None


def update_stac_for_resource(catalog: "CatalogConfig", resource: dict, namespace: str, verbose: bool = False):
    """
    Update STAC catalog with a single resource (incremental update).

    This is called when a new resource is added, avoiding full regeneration.
    """
    stac_dir = catalog.stac_dir

    # Ensure directory structure exists
    collection_dir = stac_dir / "collections" / namespace
    items_dir = collection_dir / "items"
    items_dir.mkdir(parents=True, exist_ok=True)

    # Check if root catalog exists, create if not
    catalog_path = stac_dir / "catalog.json"
    if not catalog_path.exists():
        # Full generation needed
        generate_stac_catalog(catalog, verbose=verbose)
        return

    # Update/create item
    item = _resource_to_stac_item(resource, namespace)
    item_path = items_dir / f"{resource.get('name', 'unknown')}.json"
    with open(item_path, "w") as f:
        json.dump(item, f, indent=2)

    if verbose:
        print(f"Updated STAC item: {item_path}")

    # Update collection to include new item
    collection_path = collection_dir / "collection.json"
    if collection_path.exists():
        with open(collection_path) as f:
            collection = json.load(f)

        # Add item link if not already present
        item_href = f"./items/{resource.get('name')}.json"
        existing_hrefs = [link.get("href") for link in collection.get("links", [])]
        if item_href not in existing_hrefs:
            collection["links"].append({
                "rel": "item",
                "href": item_href,
                "type": "application/geo+json",
                "title": resource.get("title", resource.get("name")),
            })
            with open(collection_path, "w") as f:
                json.dump(collection, f, indent=2)
    else:
        # Need to create collection - do full regeneration for this namespace
        generate_stac_catalog(catalog, verbose=verbose)

    # Update root catalog to include collection if new
    with open(catalog_path) as f:
        root = json.load(f)

    collection_href = f"./collections/{namespace}/collection.json"
    existing_hrefs = [link.get("href") for link in root.get("links", [])]
    if collection_href not in existing_hrefs:
        root["links"].append({
            "rel": "child",
            "href": collection_href,
            "type": "application/json",
            "title": namespace.replace("_", " ").title(),
        })
        with open(catalog_path, "w") as f:
            json.dump(root, f, indent=2)


# =============================================================================
# ISO 19139 Generator
# =============================================================================

# ISO 19139 XML namespaces
ISO_NAMESPACES = {
    "gmd": "http://www.isotc211.org/2005/gmd",
    "gco": "http://www.isotc211.org/2005/gco",
    "gml": "http://www.opengis.net/gml/3.2",
    "xsi": "http://www.w3.org/2001/XMLSchema-instance",
}


def generate_iso19139_catalog(catalog: "CatalogConfig", verbose: bool = False) -> dict[str, Path]:
    """
    Generate ISO 19139 XML metadata files from Portolan resources.

    Creates one XML file per resource following ISO 19115/19139 schema.

    Args:
        catalog: CatalogConfig with path to .portolan directory
        verbose: Print progress

    Returns:
        Dict mapping paths to created files
    """
    iso_dir = catalog.iso_dir
    iso_dir.mkdir(parents=True, exist_ok=True)

    resources_dir = catalog.path / "resources"
    if not resources_dir.exists():
        if verbose:
            print("No resources found, skipping ISO 19139 generation")
        return {}

    files_created = {}

    for namespace_dir in resources_dir.iterdir():
        if not namespace_dir.is_dir():
            continue

        namespace = namespace_dir.name
        ns_dir = iso_dir / namespace
        ns_dir.mkdir(parents=True, exist_ok=True)

        for resource_file in namespace_dir.glob("*.json"):
            if resource_file.name.startswith("_"):
                continue

            try:
                with open(resource_file) as f:
                    resource = json.load(f)

                xml_content = _resource_to_iso19139(resource)
                xml_path = ns_dir / f"{resource.get('name', 'unknown')}.xml"

                with open(xml_path, "w", encoding="utf-8") as f:
                    f.write(xml_content)

                files_created[f"{namespace}/{resource.get('name')}.xml"] = xml_path

                if verbose:
                    print(f"Created ISO 19139: {xml_path}")

            except Exception as e:
                if verbose:
                    print(f"  Error processing {resource_file}: {e}")

    if verbose:
        print(f"Generated {len(files_created)} ISO 19139 metadata files")

    return files_created


def _resource_to_iso19139(resource: dict) -> str:
    """Convert a Portolan resource to ISO 19139 XML."""
    name = resource.get("name", "unknown")
    title = resource.get("title", name)
    abstract = resource.get("abstract", "")
    spatial = resource.get("spatial_extent", {}) or {}

    # Build XML using string templates (avoiding complex XML library dependencies)
    xml = f'''<?xml version="1.0" encoding="UTF-8"?>
<gmd:MD_Metadata
    xmlns:gmd="http://www.isotc211.org/2005/gmd"
    xmlns:gco="http://www.isotc211.org/2005/gco"
    xmlns:gml="http://www.opengis.net/gml/3.2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.isotc211.org/2005/gmd http://schemas.opengis.net/iso/19139/20070417/gmd/gmd.xsd">

    <!-- File Identifier -->
    <gmd:fileIdentifier>
        <gco:CharacterString>{name}</gco:CharacterString>
    </gmd:fileIdentifier>

    <!-- Language -->
    <gmd:language>
        <gmd:LanguageCode codeList="http://www.loc.gov/standards/iso639-2/" codeListValue="eng">English</gmd:LanguageCode>
    </gmd:language>

    <!-- Hierarchy Level -->
    <gmd:hierarchyLevel>
        <gmd:MD_ScopeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_ScopeCode" codeListValue="dataset">dataset</gmd:MD_ScopeCode>
    </gmd:hierarchyLevel>

    <!-- Date Stamp -->
    <gmd:dateStamp>
        <gco:DateTime>{datetime.now(timezone.utc).isoformat()}</gco:DateTime>
    </gmd:dateStamp>

    <!-- Metadata Standard -->
    <gmd:metadataStandardName>
        <gco:CharacterString>ISO 19115:2003/19139</gco:CharacterString>
    </gmd:metadataStandardName>
    <gmd:metadataStandardVersion>
        <gco:CharacterString>1.0</gco:CharacterString>
    </gmd:metadataStandardVersion>

    <!-- Identification Info -->
    <gmd:identificationInfo>
        <gmd:MD_DataIdentification>
            <gmd:citation>
                <gmd:CI_Citation>
                    <gmd:title>
                        <gco:CharacterString>{_xml_escape(title)}</gco:CharacterString>
                    </gmd:title>
                    <gmd:date>
                        <gmd:CI_Date>
                            <gmd:date>
                                <gco:DateTime>{resource.get("created_at", datetime.now(timezone.utc).isoformat())}</gco:DateTime>
                            </gmd:date>
                            <gmd:dateType>
                                <gmd:CI_DateTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" codeListValue="creation">creation</gmd:CI_DateTypeCode>
                            </gmd:dateType>
                        </gmd:CI_Date>
                    </gmd:date>
                </gmd:CI_Citation>
            </gmd:citation>
            <gmd:abstract>
                <gco:CharacterString>{_xml_escape(abstract)}</gco:CharacterString>
            </gmd:abstract>
            <gmd:status>
                <gmd:MD_ProgressCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_ProgressCode" codeListValue="completed">completed</gmd:MD_ProgressCode>
            </gmd:status>

            <!-- Resource Format -->
            <gmd:resourceFormat>
                <gmd:MD_Format>
                    <gmd:name>
                        <gco:CharacterString>{resource.get("format", "unknown")}</gco:CharacterString>
                    </gmd:name>
                    <gmd:version>
                        <gco:CharacterString>1.0</gco:CharacterString>
                    </gmd:version>
                </gmd:MD_Format>
            </gmd:resourceFormat>

            <!-- Spatial Extent -->
            {_generate_bbox_xml(spatial)}

            <!-- Topic Category -->
            <gmd:topicCategory>
                <gmd:MD_TopicCategoryCode>geoscientificInformation</gmd:MD_TopicCategoryCode>
            </gmd:topicCategory>

        </gmd:MD_DataIdentification>
    </gmd:identificationInfo>

    <!-- Distribution Info -->
    <gmd:distributionInfo>
        <gmd:MD_Distribution>
            {_generate_distribution_xml(resource)}
        </gmd:MD_Distribution>
    </gmd:distributionInfo>

</gmd:MD_Metadata>'''

    return xml


def _xml_escape(text: str) -> str:
    """Escape special XML characters."""
    if not text:
        return ""
    return (text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
            .replace("'", "&apos;"))


def _generate_bbox_xml(spatial: dict) -> str:
    """Generate ISO 19139 bounding box XML."""
    if not all(k in spatial for k in ["west", "south", "east", "north"]):
        return ""

    return f'''<gmd:extent>
                <gmd:EX_Extent>
                    <gmd:geographicElement>
                        <gmd:EX_GeographicBoundingBox>
                            <gmd:westBoundLongitude>
                                <gco:Decimal>{spatial["west"]}</gco:Decimal>
                            </gmd:westBoundLongitude>
                            <gmd:eastBoundLongitude>
                                <gco:Decimal>{spatial["east"]}</gco:Decimal>
                            </gmd:eastBoundLongitude>
                            <gmd:southBoundLatitude>
                                <gco:Decimal>{spatial["south"]}</gco:Decimal>
                            </gmd:southBoundLatitude>
                            <gmd:northBoundLatitude>
                                <gco:Decimal>{spatial["north"]}</gco:Decimal>
                            </gmd:northBoundLatitude>
                        </gmd:EX_GeographicBoundingBox>
                    </gmd:geographicElement>
                </gmd:EX_Extent>
            </gmd:extent>'''


def _generate_distribution_xml(resource: dict) -> str:
    """Generate ISO 19139 distribution info XML."""
    assets = resource.get("assets", {})

    if not assets:
        return ""

    transfers = []
    for asset_key, asset_info in assets.items():
        if isinstance(asset_info, dict) and asset_info.get("href"):
            transfers.append(f'''<gmd:transferOptions>
                <gmd:MD_DigitalTransferOptions>
                    <gmd:onLine>
                        <gmd:CI_OnlineResource>
                            <gmd:linkage>
                                <gmd:URL>{_xml_escape(asset_info["href"])}</gmd:URL>
                            </gmd:linkage>
                            <gmd:name>
                                <gco:CharacterString>{_xml_escape(asset_info.get("title", asset_key))}</gco:CharacterString>
                            </gmd:name>
                            <gmd:function>
                                <gmd:CI_OnLineFunctionCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_OnLineFunctionCode" codeListValue="download">download</gmd:CI_OnLineFunctionCode>
                            </gmd:function>
                        </gmd:CI_OnlineResource>
                    </gmd:onLine>
                </gmd:MD_DigitalTransferOptions>
            </gmd:transferOptions>''')

    return "\n".join(transfers)


def update_iso19139_for_resource(catalog: "CatalogConfig", resource: dict, namespace: str, verbose: bool = False):
    """
    Update ISO 19139 catalog with a single resource (incremental update).
    """
    iso_dir = catalog.iso_dir
    ns_dir = iso_dir / namespace
    ns_dir.mkdir(parents=True, exist_ok=True)

    xml_content = _resource_to_iso19139(resource)
    xml_path = ns_dir / f"{resource.get('name', 'unknown')}.xml"

    with open(xml_path, "w", encoding="utf-8") as f:
        f.write(xml_content)

    if verbose:
        print(f"Updated ISO 19139: {xml_path}")


# =============================================================================
# Main Update Function
# =============================================================================

def update_all_outputs(catalog: "CatalogConfig", resource: dict, namespace: str, verbose: bool = False):
    """
    Update all enabled output formats for a resource.

    Called when a new resource is added via `dataset add` or `import`.
    """
    outputs = catalog.outputs

    # Iceberg is always updated by the main code

    if outputs.get("stac"):
        update_stac_for_resource(catalog, resource, namespace, verbose=verbose)

    if outputs.get("iso19139"):
        update_iso19139_for_resource(catalog, resource, namespace, verbose=verbose)


def regenerate_all_outputs(catalog: "CatalogConfig", verbose: bool = False):
    """
    Regenerate all enabled output formats from scratch.

    Called by `portolan rebuild`.
    """
    outputs = catalog.outputs

    if outputs.get("stac"):
        if verbose:
            print("Regenerating STAC catalog...")
        generate_stac_catalog(catalog, verbose=verbose)

    if outputs.get("iso19139"):
        if verbose:
            print("Regenerating ISO 19139 metadata...")
        generate_iso19139_catalog(catalog, verbose=verbose)
